name: Build Skybridge Mock APK

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Scaffold Missing Android Files
        run: |
          flutter create temp_app --platforms=android
          mv temp_app/android ./
          rm -rf temp_app
        working-directory: frontend

      - name: Auto-Fix Dart SDK Version
        run: sed -i 's/>=2.17.0 <3.0.0/>=3.0.0 <4.0.0/g' pubspec.yaml
        working-directory: frontend

      - name: Get Dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Build APK (Release mode)
        run: flutter build apk --release
        working-directory: frontend

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: skybridge-mock-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
